services:
    shogmar_first_commnd.create_uuid_command:
        class: App\shogmar\UuidConsoleBundle\Command\CreateUuidCommand
        tags:
            - { name: console.command, command: shogmar:create-uuid}